# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analytics.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'analytics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61nalytics.proto\x12\tanalytics\" \n\x10\x41nalyticsRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x01\"H\n\x11\x41nalyticsResponse\x12\x0c\n\x04mean\x18\x01 \x01(\x01\x12\x0b\n\x03max\x18\x02 \x01(\x01\x12\x0b\n\x03min\x18\x03 \x01(\x01\x12\x0b\n\x03sum\x18\x04 \x01(\x01\x32X\n\x10\x41nalyticsService\x12\x44\n\x07\x43ompute\x12\x1b.analytics.AnalyticsRequest\x1a\x1c.analytics.AnalyticsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analytics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANALYTICSREQUEST']._serialized_start=30
  _globals['_ANALYTICSREQUEST']._serialized_end=62
  _globals['_ANALYTICSRESPONSE']._serialized_start=64
  _globals['_ANALYTICSRESPONSE']._serialized_end=136
  _globals['_ANALYTICSSERVICE']._serialized_start=138
  _globals['_ANALYTICSSERVICE']._serialized_end=226
# @@protoc_insertion_point(module_scope)
