version: "3.8"

services:
  vit_manager:
    build: ./vIT-Management
    container_name: vit_manager
    ports:
      - "9960:9960"
    networks:
      - IT_NETWORK
      - OT_NETWORK
    labels:
      domain: "IT_DOMAIN"
  
  mqtt_broker:
    image: eclipse-mosquitto:2
    container_name: mqtt_broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - IT_NETWORK
      - OT_NETWORK
    labels:
      domain: "OT_DOMAIN"  

  vplc:
    image: docker.io/shanewardmsc/sdcs-x-openplc:v1.10
    container_name: vplc
    ports:
      - "502:502"       # Modbus TCP
      - "8080:8080"     # OpenPLC Web UI
    depends_on:
      - mqtt_broker
    networks:
      - OT_NETWORK
    environment:
      TAGS_FILE: /app/plc_tags.csv
    labels:
      domain: "OT_DOMAIN"
      
  vhis:
    image: shanewardmsc/sdcs-x-influxdb:v1.17
    container_name: vhis
    ports:
      - "8086:8086"
    depends_on:
      - mqtt_broker
    networks:
      - OT_NETWORK
    restart: always
    environment:
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: password
      MQTT_BROKER: mqtt_broker
      INFLUX_URL: http://localhost:8086
      INFLUX_TOKEN: v0pWVk7e_RnmNMVce6JRRyIYiFmGLJNx5g2s3bgwELODB1O9n61URR6B_hBUkN1fhmvO6ks7zSGaprG9m0GKDA==
      INFLUX_ORG: MTU
      INFLUX_BUCKET: vHIS
      TAGS_FILE: /app/plc_tags.csv
    volumes:
      - influxdb_data:/var/lib/influxdb2
    labels:
      domain: "OT_DOMAIN"


  vot_manager:
    build: ./vOT-Management
    container_name: vot_manager
    privileged: true
    ports:
      - "9970:9970"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    depends_on:
      - mqtt_broker
    networks:
      - IT_NETWORK
      - OT_NETWORK
    labels:
      domain: "OT_DOMAIN"


  vhmi:
    image: docker.io/shanewardmsc/sdcs-x-grafana:v1.0
    container_name: vhmi
    ports:
      - "3000:3000"
    depends_on:
      - vhis
      - mqtt_broker
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    networks:
      - OT_NETWORK
    volumes:
      - grafana_data:/var/lib/grafana
    labels:
      domain: "OT_DOMAIN"

networks:
  IT_NETWORK:
  OT_NETWORK:

volumes:
  influxdb_data:
  grafana_data:

