version: "3.8"

services:
  mqtt_broker:
    image: eclipse-mosquitto:2
    container_name: mqtt_broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - OT_NETWORK
    labels:
      domain: "OT_DOMAIN"  

  vplc:
    image: docker.io/shanewardmsc/sdcs-x-openplc:v1.4
    container_name: vplc
    ports:
      - "502:502"       # Modbus TCP
      - "8080:8080"     # OpenPLC Web UI
    depends_on:
      - mqtt_broker
    networks:
      - OT_NETWORK
    labels:
      domain: "OT_DOMAIN"

  modbus_mqtt:
    build: ./modbus_mqtt
    container_name: modbus_mqtt
    depends_on:
      - vplc
      - mqtt_broker
    networks:
      - OT_NETWORK
    volumes:
      - ./modbus_mqtt:/app
    environment:
      - MQTT_BROKER=mqtt_broker  # or container name
    labels:
      domain: "OT_DOMAIN"
  
  vhis:
    image: docker.io/shanewardmsc/sdcs-x-influxdb:v1.5
    container_name: vhis
    ports:
      - "8086:8086"
    depends_on:
      - mqtt_broker 
    networks:
      - OT_NETWORK
    restart: always
    environment:
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: password
    volumes:
      - influxdb_data:/var/lib/influxdb2
    labels:
      domain: "OT_DOMAIN"

  vot_manager:
    build: ./vOT-Management
    container_name: vot_manager
    ports:
      - "9970:9970"
    depends_on:
      - mqtt_broker
    networks:
      - OT_NETWORK
    labels:
      domain: "OT_DOMAIN"    
      
  mqtt_to_influx:
    build: ./mqtt_to_influx
    environment:
      - MQTT_BROKER=mqtt_broker
      - INFLUX_URL=http://vhis:8086
      - INFLUX_TOKEN=v0pWVk7e_RnmNMVce6JRRyIYiFmGLJNx5g2s3bgwELODB1O9n61URR6B_hBUkN1fhmvO6ks7zSGaprG9m0GKDA==
      - INFLUX_ORG=MTU
      - INFLUX_BUCKET=vHIS
    depends_on:
      - mqtt_broker
      - vhis
    networks:
      - OT_NETWORK
    labels:
      domain: "OT_DOMAIN"
      
  vhmi:
    image: docker.io/shanewardmsc/sdcs-x-grafana:v1.0
    container_name: vhmi
    ports:
      - "3000:3000"
    depends_on:
      - vhis
      - mqtt_broker
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    networks:
      - OT_NETWORK
    volumes:
      - grafana_data:/var/lib/grafana
    labels:
      domain: "OT_DOMAIN"

networks:
  IT_NETWORK:
  OT_NETWORK:

volumes:
  influxdb_data:
  grafana_data:

